import esbuild from 'esbuild';
import { readFileSync } from 'fs';

const banner = `/*\n * This file is generated by esbuild.\n * ${new Date().toISOString()}\n */`;

const watch = process.argv.includes('--watch');

const ctx = await esbuild.context({
  entryPoints: ['src/main.ts'],
  bundle: true,
  format: 'cjs',
  target: 'es2018',
  platform: 'browser',
  external: ['obsidian'],
  outfile: 'main.js',
  sourcemap: process.env.BUILD === 'production' ? false : true,
  banner: { js: banner },
});

if (watch) {
  await ctx.watch();
  console.log('Watching for changes...');
} else {
  await ctx.rebuild();
  await ctx.dispose();
}
